// This file was generated by SPL Measurement Code Generator 
// #9939ae0d|local|THIS@/Users/lottiecarruthers/Documents/Masters/Project/HelloWorldSPL/output/.spl/temporary/build-0/sourceCode/revision-0-20160701142639:main.HelloWorld#hello4(String)[THIS@/Users/lottiecarruthers/Documents/Masters/Project/HelloWorldSPL/output/.spl/temporary/build-0/sourceCode/revision-0-20160701142639:main.StringGenerator#generate()](10)


@SuppressWarnings("unchecked")
public class CSGenerator implements ISGenerator {

    @Override
    public Iterable<Object[]> newInstance() throws Throwable {


        java.util.ArrayList generator = new main.StringGenerator (




            )

            . generate(
                            10
                )

            ;


        return generator;
    }
}

