// This file was generated by SPL Measurement Code Generator 


public interface ISMethod {

    public void newInstance() throws Throwable;

    public void call(Object[] arguments) throws Throwable;
}
