// This file was generated by SPL Measurement Code Generator 
// #9939ae0d|local|THIS@/Users/lottiecarruthers/Documents/Masters/Project/HelloWorldSPL/output/.spl/temporary/build-0/sourceCode/revision-0-20160701142639:main.HelloWorld#hello4(String)[THIS@/Users/lottiecarruthers/Documents/Masters/Project/HelloWorldSPL/output/.spl/temporary/build-0/sourceCode/revision-0-20160701142639:main.StringGenerator#generate()](10)


public class CSMethod implements ISMethod {

        private main.HelloWorld fInstance;
    
    public void newInstance() throws Throwable {
                this.fInstance = new main.HelloWorld(
                    );
            }


    public void call(Object[] arguments) throws Throwable{
                this.fInstance
        
        . hello4 (

                                        (java.lang.String) arguments[0]
                    );
    }
}

